# numpy inf和nan

In [1]:
'''
C 语言中表示最大的正整数值是 0x7FFFFFFF，最小的负整数是 0x80000000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有 float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现inf呢？ 比如一个数字除以0，Python中会报错，但是numpy中会是一个inf或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。任何与其做运算结果都是 nan
'''
import numpy as np
#nan 是not a number的缩写，表示非数字，在numpy中表示一个非数字值，可以用来表示缺失数据
# 创建一个nan和inf
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))

nan <class 'float'>
inf <class 'float'>


In [4]:
# 并 且  np.nan != np.nan 结果 是TRUE
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan == np.nan)
print(np.inf == np.inf)
np.nan + 1  #nan和其他数运算的结果都是nan

False
True


nan

In [6]:
# 判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)
# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)
# 可以使用np.count_nonzero() 来判断非零的个数
# print(np.count_nonzero(t))
print(t != t)
print('-' * 50)
print(np.count_nonzero(t != t))  # 统计nan的个数
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]
[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
--------------------------------------------------
2
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [7]:
# ----------练习： 处理数组中nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-------------------')
print(t.shape)
print(id(t))
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:, i]

    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有nan
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来,并计算平均值
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)

print(t)
print(id(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
(4, 6)
2039197796464
[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
2039197796464


In [9]:
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])  #1除0就会得到inf

[-1  0]
-inf


C:\Users\12268\AppData\Local\Temp\ipykernel_20064\2586930737.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0] / arr[1])  #1除0就会得到inf


# 转置和轴滚动

In [10]:
#对换数组的维度
import numpy as np

a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)
print('\n')

print('对换数组：')
print(np.transpose(a))
print(a)

# 与transpose一致
a = np.arange(12).reshape(3, 4)

print('原数组：')
print(a)
print('\n')

print('转置数组：')
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [11]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
re1 = t1.swapaxes(1, 0)

print('原数组：')
print(t1)
print('\n')
print(re1.shape)
print('调用swapaxes函数后的数组：')
print(re1)

原数组：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


(6, 4)
调用swapaxes函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [12]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)

(3, 4, 5)
--------------------------------------------------
(3, 5, 4)


In [13]:
# 数组的轴滚动,swapaxes每次只能交换两个轴，没有rollaxis方便，默认情况下轴滚动最前面
a = np.ones((3, 4, 5, 6))
# np.rollaxis(a, 2).shape
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [14]:
#数据拷贝，copy()和赋值的区别
b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()
print(a)
b[0, 0] = 3
print(b)
a

[[1 2 3]
 [1 2 3]]
[[3 2 3]
 [1 2 3]]


array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
#随机数生成
arr = np.random.rand(2, 3, 4)
print(arr)

[[[0.59246343 0.87233169 0.54194515 0.13821015]
  [0.98906254 0.01222322 0.27051602 0.7899792 ]
  [0.62449183 0.38803406 0.22581524 0.93468632]]

 [[0.05098918 0.6984077  0.94898482 0.89435528]
  [0.83031422 0.22950717 0.13566803 0.5491782 ]
  [0.6416106  0.44953346 0.54839056 0.72968012]]]
